# Generated by Django 2.2.5 on 2021-07-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title', max_length=100)),
                ('contents', models.TextField(help_text='post contents')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('u_id', models.CharField(db_column='u_id', max_length=20, primary_key=True, serialize=False)),
                ('r_id', models.IntegerField(db_column='r_id')),
                ('r_num', models.IntegerField(db_column='r_num')),
                ('comment', models.TextField(db_column='rv_review')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='rv_regdate')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeapp.Post')),
            ],
        ),
    ]
